"use client";

import { useRef } from "react";
import BlogLayout from "@/components/blog-layout";
import Image from "next/image";
import Script from "next/script";
import { Calendar } from "lucide-react";
import RelatedPosts from "@/components/related-posts";
import ShareButtons from "@/components/share-buttons";
import BackToTop from "@/components/BackToTop";
import BlogEnhancements from "@/components/blog-enhancements";
import BlogBackButton from "@/components/BlogBackButton";
import "@/styles/blog.css";
import "@/styles/enhanced-blog.css";

export default function BlogPostPage() {
  const articleRef = useRef<HTMLElement>(null);
  const postUrl = typeof window !== 'undefined' ? window.location.href : '';

  return (
    <BlogLayout>
      <div className="blog-container max-w-3xl mx-auto">
        <BlogEnhancements target={articleRef} />
        
        <article ref={articleRef} className="prose prose-lg dark:prose-invert max-w-none">
          <header className="mb-8">
            <div className="flex flex-wrap items-center gap-2 mb-4">
              <BlogBackButton className="!mr-2" />
              <span className="blog-category category-education">Education</span>
              <span className="blog-category category-trading">Trading</span>
            </div>
            <h1>Technical Analysis: Fundamentals for Beginners</h1>

            <div className="article-metadata">
              <div className="flex items-center">
                <Image 
                  src="/placeholder-user.jpg"
                  alt="Author"
                  width={24}
                  height={24}
                  className="author-avatar"
                />
                <span>Exchangetime Team</span>
              </div>
              <span className="separator">•</span>
              <div className="flex items-center">
                <Calendar size={14} className="mr-1" />
                <span>August 5, 2025</span>
              </div>
            </div>

            <ShareButtons title="Technical Analysis: Fundamentals for Beginners" url={postUrl} />
          </header>
          
          <div className="relative w-full h-80 mb-6 rounded-lg overflow-hidden">
            <Image 
              src="https://images.unsplash.com/photo-1535320903710-d993d3d77d29?auto=format&fit=crop&w=1200&h=675"
              alt="Technical Analysis Chart"
              fill
              priority
              className="object-cover"
            />
          </div>

          <hr className="my-8 border-neutral-200 dark:border-neutral-800" />
          
          <h2>Introduction to Technical Analysis</h2>
          <p>
            Technical analysis is a method of evaluating securities by analyzing statistics generated by market activity, such as past prices and volume. Unlike fundamental analysis, which attempts to evaluate a security's intrinsic value, technical analysis focuses exclusively on price movement patterns and trading volume to predict future price movements.
          </p>
          
          <h2>The Basic Principles of Technical Analysis</h2>
          <p>
            Technical analysis is based on three essential principles:
          </p>
          <ol>
            <li><strong>Markets discount everything</strong> - Prices reflect all available information that can affect the value of an asset.</li>
            <li><strong>Prices move in trends</strong> - Prices often follow recognizable trends that last longer than random movements.</li>
            <li><strong>History repeats itself</strong> - Price patterns that have occurred in the past are likely to occur again in the future.</li>
          </ol>
          
          <h2>Basic Chart Types</h2>
          <p>
            To begin with technical analysis, it's important to understand different chart types:
          </p>
          <ul>
            <li><strong>Line charts</strong> - The simplest form of charts, showing the closing price over a specific period.</li>
            <li><strong>Bar charts</strong> - Show opening, high, low, and closing prices for each period.</li>
            <li><strong>Candlestick charts</strong> - Similar to bar charts, but with a visual representation that makes it easier to recognize patterns.</li>
          </ul>
          
          <h3>Understanding Candlestick Charts</h3>
          <p>
            Candlestick charts are particularly popular in technical analysis because they are easy to read and visually represent important information:
          </p>
          <ul>
            <li>The "body" of the candle shows the range between the opening and closing price.</li>
            <li>A filled (often red) body indicates that the closing price was below the opening price (bearish).</li>
            <li>An empty (often green) body indicates that the closing price was above the opening price (bullish).</li>
            <li>The "wicks" or "shadows" above and below the body show the highest and lowest levels during the trading period.</li>
          </ul>
          
          <h2>Recognizing Important Chart Patterns</h2>
          <p>
            Chart patterns are specific formations that occur in price charts and can signal certain market movements:
          </p>
          
          <h3>Trend Reversal Patterns</h3>
          <ul>
            <li><strong>Head and Shoulders Formation</strong> - A pattern with three peaks, where the middle peak (head) is higher than the two outer ones (shoulders). This pattern often signals a trend reversal from bullish to bearish.</li>
            <li><strong>Double Top and Double Bottom</strong> - M-shaped (Double Top) or W-shaped (Double Bottom) patterns that indicate resistance or support and potential trend reversal.</li>
          </ul>
          
          <h3>Continuation Patterns</h3>
          <ul>
            <li><strong>Flags and Pennants</strong> - Short consolidation phases within an existing trend, often indicating a continuation of the previous trend.</li>
            <li><strong>Triangles</strong> - Convergent trend lines that represent a period of consolidation before the market breaks out in a specific direction.</li>
          </ul>
          
          <h2>Technical Indicators</h2>
          <p>
            Technical indicators are mathematical calculations based on the price, volume, or open interest of a security. They are used to predict future price changes.
          </p>
          
          <h3>Trend Following Indicators</h3>
          <p>
            These indicators help determine the direction and strength of a trend:
          </p>
          <ul>
            <li><strong>Moving Averages</strong> - The average of prices over a specific period, which helps identify the long-term trend.</li>
            <li><strong>MACD (Moving Average Convergence Divergence)</strong> - Measures the relationship between two moving averages and signals momentum changes.</li>
          </ul>
          
          <h3>Oscillators</h3>
          <p>
            These indicators move between fixed values and help identify overbought or oversold conditions:
          </p>
          <ul>
            <li><strong>RSI (Relative Strength Index)</strong> - Measures the speed and change of price movements and oscillates between 0 and 100.</li>
            <li><strong>Stochastic</strong> - Compares the current closing price with its price range over a specific period.</li>
          </ul>
          
          <h2>Support and Resistance</h2>
          <p>
            Support and resistance levels are price areas where the market has historically reacted:
          </p>
          <ul>
            <li><strong>Support</strong> - A price area below which an asset finds it difficult to fall, as buyers typically take control.</li>
            <li><strong>Resistance</strong> - A price area above which an asset finds it difficult to rise, as sellers typically take control.</li>
          </ul>
          <p>
            When a price breaks through a support or resistance line, this can be an important signal and often lead to significant price movements.
          </p>
          
          <h2>Practical Application for Beginners</h2>
          <p>
            For beginners in technical analysis, we recommend the following steps:
          </p>
          <ol>
            <li><strong>Start simple</strong> - Initially focus on a few, basic indicators and patterns.</li>
            <li><strong>Practice chart reading</strong> - Analyze historical charts and identify known patterns and how the market has reacted to them.</li>
            <li><strong>Combine multiple indicators</strong> - A single indicator can be misleading; look for confirmation through various analysis methods.</li>
            <li><strong>Keep a trading journal</strong> - Document your analyses and results to learn from successes and failures.</li>
          </ol>
          
          <h2>Conclusion</h2>
          <p>
            Technical analysis is a powerful tool for traders and investors, but it requires practice and experience to use effectively. By understanding the basic principles, chart patterns, and indicators, you can make better trading decisions and improve your ability to anticipate market movements.
          </p>
          <p>
            Remember that no analysis method is perfect. The best results are often achieved when technical analysis is combined with fundamental analysis and solid risk management.
          </p>

          {/* Bottom share */}
          <ShareButtons title="Technical Analysis: Fundamentals for Beginners" url={postUrl} />

          {/* JSON-LD */}
          <Script id="ta-article-ld" type="application/ld+json" strategy="afterInteractive"
            dangerouslySetInnerHTML={{
              __html: JSON.stringify({
                "@context": "https://schema.org",
                "@type": "Article",
                headline: "Technical Analysis: Fundamentals for Beginners",
                datePublished: "2025-08-05",
                author: [{ "@type": "Organization", name: "Exchangetime Team" }],
                image: [
                  "https://images.unsplash.com/photo-1535320903710-d993d3d77d29?auto=format&fit=crop&w=1200&h=675"
                ],
                mainEntityOfPage: postUrl || undefined,
                description: "Technical analysis basics, chart patterns, and indicators for beginners.",
              })
            }}
          />
        </article>
        
        {/* Related Articles */}
        <RelatedPosts currentPostSlug="technische-analyse-grundlagen" />
        <BackToTop target={articleRef} threshold={160} />
      </div>
    </BlogLayout>
  );
}
